# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5nulcgZsmM1qVvqFlygS3asD0-_Z996
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

def check_if_line_is_straight(image_path, deviation_threshold=5):

    image = cv2.imread(image_path)
    output_image = image.copy()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


    edges = cv2.Canny(gray, 50, 150)


    lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=100, minLineLength=100, maxLineGap=10)
    if lines is None:
        return False, image


    straight = True
    for line in lines:
        x1, y1, x2, y2 = line[0]

        angle = abs(np.arctan2(y2 - y1, x2 - x1) * 180 / np.pi)
        if not (90 - deviation_threshold <= angle <= 90 + deviation_threshold):
            straight = False


        cv2.line(output_image, (x1, y1), (x2, y2), (0, 255, 0), 3)

    return straight, output_image

file_path1 = "/content/Image1.jpeg"


is_straight1, processed_image1 = check_if_line_is_straight(file_path1, deviation_threshold=5)


plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(processed_image1, cv2.COLOR_BGR2RGB))
plt.title(f"Straight : {is_straight1}")
plt.axis("off")

plt.show()